version: 2

updates:
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Paris
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 2
    groups:
      prod:
        dependency-type: production
      dev:
        dependency-type: development
